[package]
name = "dsd2dxd"
version = "2.2.1"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive", "wrap_help"] }
rand = "0.8"
flac-codec = "1.2.0"
dsf = { path = "src/dsf/" }
dff-meta = "0.1.0"
id3 = "1.16.3"